package br.dev.allan.controlefinanceiro.domain.model

enum class TransactionCategory {
    // EXPENSES
    CREDIT_CARD_PAYMENT,
    SAVINGS,
    HOUSING,
    ENERGY_BILL,
    WATER_BILL,
    GAS_BILL,
    FOOD,
    DRINK,
    TRANSPORTATION,
    UBER,
    GROCERIES,
    ENTERTAINMENT,
    SHOPPING,
    HEALTH_PERSONAL_CARE,
    EDUCATION,
    SUBSCRIPTIONS,
    DEBT_REPAYMENT,
    INVESTMENT_OUT,
    TRAVEL,
    PETS,
    GIFTS_DONATION,
    MAINTENANCE,
    TAXES,
    INSURANCE,
    OTHERS_EXPENSE,

    // INCOME
    SALARY,
    FREELANCE,
    INVESTMENTS,
    GIFTS_RECEIVED,
    RENTAL_INCOME,
    REFUNDS,
    BONUS,
    GRANTS,
    SALES,
    OTHERS_INCOME
}